#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: SymfonyClient\Controller
#    type: attribute
health:
    path: /
    controller: SymfonyClient\Controller\HealthController
    methods: [GET]
