health:
    path: /health
    controller: SymfonyClient\Controller\HealthController
    methods: [GET]

create-user:
    path: /user
    controller: SymfonyClient\Controller\CreateUserController
    methods: [POST]

retrieve-user:
    path: /user/{userId}
    controller: SymfonyClient\Controller\RetrieveUserController
    methods: [GET]
